### ISSUE TITLE
Panic if quit without selecting

### ISSUE THREAD

**Issue by jvijay-work** [cqroot/prompt#1]
Panic if quit without selecting

```go
package main

import (
        "fmt"
        "os"

        "github.com/cqroot/prompt"
)

func main() {
        val, err := prompt.New().Ask("Choose value:").SetHelpVisible(true).
                Choose([]string{"Item 1", "Item 2", "Item 3"})
        if err != nil {
                fmt.Println("Error:", err)
                os.Exit(1)
        }
        fmt.Println("Val:", val)
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4eb26f]
```

**Comment by cqroot** [comment]
It has been fixed in v0.3.0 and added tests to cover it.

**Comment by nopdan** [comment]
@cqroot Pressing ctrl+c and q to exit is normal, but clicking the close button to exit will first block for 2 seconds before closing.

**Comment by nopdan** [comment]
> @cqroot Pressing ctrl+c and q to exit is normal, but clicking the close button to exit will first block for 2 seconds before closing.

This seems to be an upstream problem. I tried https://github.com/erikgeiser/promptkit. It's same.
