### ISSUE TITLE
Is it possible to set default selected options in multichoose?

### ISSUE THREAD

**Issue by mutsuki333** [cqroot/prompt#24]
Thanks for this great repo!!

I was wondering if `Choose` and `MultiChoose` could support default values, it would be a great UX improvement if the prompts could pre-select some default choices for the user.

I noticied that there is a private field ([mc](https://github.com/cqroot/prompt/blob/ccee86e59e46911057bc7bd377b30d42db999359/multichoose/multichoose.go#L15)) to keep track of the selected options. Is it possible to make it public or allow a option method to access the underlying field?

**Comment by cqroot** [comment]
#25 

Examples:

- https://github.com/cqroot/prompt/blob/47405bf7476f56e71d201149faa063dbc63d368e/_examples/choose/main.go#L31
- https://github.com/cqroot/prompt/blob/47405bf7476f56e71d201149faa063dbc63d368e/_examples/multichoose/main.go#L32
