### ISSUE TITLE
How to go about testing inputs and outputs?

### ISSUE THREAD

**Issue by miniscruff** [cqroot/prompt#7]
Currently I have been passing a reader and writer to my existing prompt tool for testing. Is there a way of doing that here or is there some other means of testing? I was looking for a way of passing a tea.WithOutput or tea.WithInput but do not see how.

**Comment by cqroot** [comment]
Currently this package does not support passing a `tea.ProgramOption`.

When I was testing this package, I used `tea.NewProgram(model, tea.WithInput(&in), tea.WithOutput(&out)).Run()` to pass in input. Can be found [here](https://github.com/cqroot/prompt/blob/7d6f0e67f9c7c95c091d88e2e91c753f133e5eff/tester/model.go#LL27C19-L27C19)

`prompt.Prompt` itself and `input.Model` etc. implement `tea.Model`.

I will update this package later to make it easier for users to pass `tea.ProgramOption`.

**Comment by cqroot** [comment]
In v0.8.4, you can pass `tea.ProgramOption` to prompt.

Example [here](https://github.com/cqroot/prompt/blob/90658587b81eff9f9c79be265247f8fa0153f814/examples/tea-program-options/main.go).

**Comment by miniscruff** [comment]
This looks good to me, going to close this. Thanks.
