### ISSUE TITLE
Error is not returned if validation fails

### ISSUE THREAD

**Issue by miniscruff** [cqroot/prompt#8]
When running a prompt with an input validation, if you submit a value that fails validation, no error is returned back to let the upper program know.

Eg in this example: https://github.com/cqroot/prompt/blob/main/examples/input-with-validation/main.go, if you were to submit an invalid ip it just works. I believe the correct scenario would be that `.Ask(...).Input(...)` would return `"", <error returned from validation>`. 

# what happens in the validation example
```sh
prompt/examples/input-with-validation  main ✔
▶ go run main.go
✔ Please enter the server IP: … invalid ip address
invalid ip address   # this should be the "is not a valid ip" error
```

**Comment by cqroot** [comment]
I fixed it in v0.8.6.

An updated example can be seen [here](https://github.com/cqroot/prompt/blob/039453cf7b6be2f9bdeaa22c08545392a1f5b5f4/examples/input-with-validation/main.go).
