### ISSUE TITLE
Validation option for Write text blocks

### ISSUE THREAD

**Issue by miniscruff** [cqroot/prompt#9]
Hey, its me again :smirk:

I would like to add validations to write text blocks identical to the input text.
Not sure what other info you would need but let me know, I can also probably create a PR if you want.

**Comment by cqroot** [comment]
Good advice. I will add this feature later.

**Comment by cqroot** [comment]
I added validation option to `write` in v0.8.7. It has the same implementation as `input`. [Here](https://github.com/cqroot/prompt/blob/712a7f7eb128b677067f57697194b1332829514a/examples/write-with-validation/main.go) is an example.

In addition, I removed the ✔ display when the validation was successful. Personally, I think it looks better this way.

**Comment by miniscruff** [comment]
> I added validation option to `write` in v0.8.7. It has the same implementation as `input`. [Here](https://github.com/cqroot/prompt/blob/712a7f7eb128b677067f57697194b1332829514a/examples/write-with-validation/main.go) is an example.
> 
> In addition, I removed the ✔ display when the validation was successful. Personally, I think it looks better this way.

Awesome, I will give this a try soon
